server:
  port: ${PORT:9001}


spring:
  application:
    name: auth2-client
  #redis配置数据
  redis:
    port: 6379
    database: 0
    password: 2mSbVpO0
    timeout: 5000
    host: 127.0.0.1




ignore:
  urls:
    - /ignoreAuth/**

